name: first gigt
on: push
jobs:
  job1:
    name: to print hello
    runs-on: ubuntu-latest
    steps:
      - name: to print
        run: |
            echo "hello world"
            echo "name is "
  job2:
    name: to print hello
    runs-on: ubuntu-latest
    steps:
      - name: to print
        run: |
            echo "orld"
            echo "nme is "
